default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: ''
  socket: /home/linuxbrew/.linuxbrew/var/mysql/mysql.sock

development:
  <<: *default
  database: chat_with_openaiapi_development
  
production:
  <<: *default
  database: chat_with_openaiapi_production
  username: chat_with_openaiapi
  password: <%= ENV["CHAT_WITH_OPENAIAPI_DATABASE_PASSWORD"] %>